baseURL = 'https://syndrome-impostor.github.io/'
languageCode = 'en-us'
title = "Blog"
theme = "papermod"

[params]
  description = "Security research, bug bounty hunting, and OAuth/OIDC vulnerability analysis"

  [params.homeInfoParams]
    Title = "Syndrome Impostor"
    Content = "Security Researcher // OAuth & OIDC Specialist // Bug Bounty Hunter"
  
  # Social Icons for the entire site
  [[params.socialIcons]]
    name = "twitter"
    url = "https://x.com/Syndromeimpostr"
    
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/syndrome-impostor"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/scott-infosec/"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "cves"
    name = "CVEs"
    url = "/cves/"
    weight = 9